package gestion_de_asistencia;

import Clases.Licencia;
import Clases.Usuario;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;
import java.util.Date;
import java.util.Calendar;
import Clases_BD.Comm_BD;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import Clases.Sesion_Usuario;
/**
 *
 * @author dolan
 */
public class Interfaz_AusenciaLaboral extends javax.swing.JFrame {

    String Seguro;
    private Comm_BD bd;
    private Usuario U_Loggeado;
    /**
     * Creates new form Interfaz_AusenciaLaboral
     */
    public Interfaz_AusenciaLaboral(JFrame Anterior, String Contrasena, Usuario usuario) {
    initComponents();
    initComponentesPersonalizados();
    bd = new Comm_BD();
    Seguro = Contrasena;
    this.U_Loggeado = usuario;  
    if (usuario != null) {
        Sesion_Usuario.setUsuario(usuario);
    }
    setLocationRelativeTo(null);
}
    public Interfaz_AusenciaLaboral() {
    initComponents();
    initComponentesPersonalizados();
    bd = new Comm_BD();
    Seguro = "";
    
    // Crear usuario directamente
    U_Loggeado = new Usuario();
    U_Loggeado.setNombre("Usuario Testing");
    U_Loggeado.setApellido("Prueba");
    
    setLocationRelativeTo(null);
}

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
     private void configurarVentana() {
    setSize(500, 450);
    setMinimumSize(new java.awt.Dimension(500, 450));
}
     

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @SuppressWarnings("unchecked")
    private void initComponentesPersonalizados(){
        
        
    jDesktopPane1 = new javax.swing.JDesktopPane();
    jDesktopPane1.setBackground(new java.awt.Color(245, 245, 245));
    
    // Agregarlo al JFrame como componente principal
    getContentPane().removeAll();
    getContentPane().setLayout(new java.awt.BorderLayout());
    getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    
    // ============= CONTINUAR CON LA LÓGICA ORIGINAL =============
    
    

        // Crear los componentes adicionales
        crearComponentesAdicionales();

        // Configurar propiedades de los componentes
        configurarComponentesAdicionales();

        // Agregar eventos a los botones
        agregarEventosComponentes();

        // Configurar layout personalizado
        configurarLayoutPersonalizado();

        // Configuración final de la ventana
        configurarVentana();
    }
    
    private void crearComponentesAdicionales() {
        // Crear componentes que no están en el initComponents() de NetBeans
        tf_RutEmpleado = new javax.swing.JTextField();
        cb_TipoAusencia = new javax.swing.JComboBox<>();
        ta_Motivo = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane(ta_Motivo);
        btn_RegistrarAusencia = new javax.swing.JButton();
        btn_Volver = new javax.swing.JButton();
        btn_BuscarEmpleado = new javax.swing.JButton();
        lbl_NombreEmpleado = new javax.swing.JLabel();

        // Crear los JDateChooser para las fechas
        dc_FechaInicio = new JDateChooser();
        dc_FechaFin = new JDateChooser();

        // Crear etiquetas adicionales
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
    }
    
    private void configurarComponentesAdicionales() {
        // Configurar título de la ventana
        setTitle("Registro de Ausencias Laborales");
        setResizable(false);

        // Configurar título principal
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18));
        jLabel1.setText("Registro de Ausencias Laborales");
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Configurar etiquetas
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel2.setText("RUT del Empleado:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel3.setText("Fecha de Inicio:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel4.setText("Fecha de Fin:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel5.setText("Tipo de Ausencia:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14));
        jLabel6.setText("Motivo/Descripción:");

        // Configurar campo RUT
        tf_RutEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 12));
        tf_RutEmpleado.setPreferredSize(new java.awt.Dimension(150, 25));

        // Configurar label de nombre empleado
        lbl_NombreEmpleado.setFont(new java.awt.Font("Segoe UI", 2, 12));
        lbl_NombreEmpleado.setForeground(new java.awt.Color(76, 175, 80));
        lbl_NombreEmpleado.setText("Ingrese un RUT para buscar el empleado");

        // Configurar selectores de fecha
        dc_FechaInicio.setDateFormatString("dd/MM/yyyy");
        dc_FechaInicio.setPreferredSize(new java.awt.Dimension(150, 25));

        dc_FechaFin.setDateFormatString("dd/MM/yyyy");
        dc_FechaFin.setPreferredSize(new java.awt.Dimension(150, 25));

        // Configurar ComboBox de tipo de ausencia
        cb_TipoAusencia.setFont(new java.awt.Font("Segoe UI", 0, 12));
        cb_TipoAusencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "Licencia Médica", 
            "Vacaciones", 
            "Permiso Personal", 
            "Licencia por Maternidad", 
            "Licencia por Paternidad", 
            "Capacitación", 
            "Otro" 
        }));
        cb_TipoAusencia.setPreferredSize(new java.awt.Dimension(200, 25));

        // Configurar área de texto para motivo
        ta_Motivo.setColumns(25);
        ta_Motivo.setRows(4);
        ta_Motivo.setFont(new java.awt.Font("Segoe UI", 0, 12));
        ta_Motivo.setLineWrap(true);
        ta_Motivo.setWrapStyleWord(true);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 100));
        
        // Configurar botones
        btn_BuscarEmpleado.setText("Buscar");
        btn_BuscarEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 12));
        btn_BuscarEmpleado.setPreferredSize(new java.awt.Dimension(80, 25));
        
        btn_RegistrarAusencia.setText("Registrar Ausencia");
        btn_RegistrarAusencia.setBackground(new java.awt.Color(46, 125, 50));
        btn_RegistrarAusencia.setForeground(java.awt.Color.WHITE);
        btn_RegistrarAusencia.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btn_RegistrarAusencia.setPreferredSize(new java.awt.Dimension(150, 30));
        
        btn_Volver.setText("Volver");
        btn_Volver.setBackground(new java.awt.Color(156, 39, 176));
        btn_Volver.setForeground(java.awt.Color.WHITE);
        btn_Volver.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btn_Volver.setPreferredSize(new java.awt.Dimension(80, 30));
    }
    
    private void agregarEventosComponentes() {
        btn_BuscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarEmpleadoActionPerformed(evt);
            }
        });
        
        btn_RegistrarAusencia.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarAusenciaActionPerformed(evt);
            }
        });
        
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });
    }
    
    private void configurarLayoutPersonalizado() {
    // En lugar de jDesktopPane1, usar JFrame directamente
    getContentPane().setLayout(null); // Layout absoluto para setBounds
    
    // Limpiar cualquier componente existente
    getContentPane().removeAll();
    
    // Agregar componentes directamente al ContentPane
    getContentPane().add(jLabel1);
    getContentPane().add(jSeparator1);
    getContentPane().add(jLabel2);
    getContentPane().add(tf_RutEmpleado);
    getContentPane().add(btn_BuscarEmpleado);
    getContentPane().add(lbl_NombreEmpleado);
    getContentPane().add(jLabel3);
    getContentPane().add(dc_FechaInicio);
    getContentPane().add(jLabel4);
    getContentPane().add(dc_FechaFin);
    getContentPane().add(jLabel5);
    getContentPane().add(cb_TipoAusencia);
    getContentPane().add(jLabel6);
    getContentPane().add(jScrollPane1);
    getContentPane().add(btn_RegistrarAusencia);
    getContentPane().add(btn_Volver);
    
    // LAS MISMAS posiciones setBounds() - NO cambiar nada
    jLabel1.setBounds(50, 20, 350, 25);
    jSeparator1.setBounds(20, 50, 400, 2);
    jLabel2.setBounds(20, 70, 120, 25);
    tf_RutEmpleado.setBounds(150, 70, 120, 25);
    btn_BuscarEmpleado.setBounds(280, 70, 80, 25);
    lbl_NombreEmpleado.setBounds(20, 100, 400, 20);
    jLabel3.setBounds(20, 130, 120, 25);
    dc_FechaInicio.setBounds(150, 130, 150, 25);
    jLabel4.setBounds(20, 160, 120, 25);
    dc_FechaFin.setBounds(150, 160, 150, 25);
    jLabel5.setBounds(20, 190, 120, 25);
    cb_TipoAusencia.setBounds(150, 190, 200, 25);
    jLabel6.setBounds(20, 220, 150, 25);
    jScrollPane1.setBounds(20, 250, 400, 100);
    btn_RegistrarAusencia.setBounds(20, 370, 150, 30);
    btn_Volver.setBounds(180, 370, 80, 30);
    
    // Refrescar la interfaz
    revalidate();
    repaint();
}

    
 

    // ============= MÉTODOS DE EVENTOS =============
    
    private void btn_BuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {
        String rut = tf_RutEmpleado.getText().trim();
        
        if (rut.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Por favor ingrese un RUT", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            tf_RutEmpleado.requestFocus();
            return;
        }
        
        if (bd.verificarRutExiste(rut)) {
            String nombreCompleto = bd.obtenerNombreUsuario(rut);
            lbl_NombreEmpleado.setText("Empleado: " + nombreCompleto);
            lbl_NombreEmpleado.setForeground(new java.awt.Color(76, 175, 80));
        } else {
            lbl_NombreEmpleado.setText("RUT no encontrado en el sistema");
            lbl_NombreEmpleado.setForeground(java.awt.Color.RED);
        }
    }

    private void btn_RegistrarAusenciaActionPerformed(java.awt.event.ActionEvent evt) {
        // Obtener valores de los campos
        String rut = tf_RutEmpleado.getText().trim();
        Date fechaInicio = dc_FechaInicio.getDate();
        Date fechaFin = dc_FechaFin.getDate();
        String tipoAusencia = (String) cb_TipoAusencia.getSelectedItem();
        String motivo = ta_Motivo.getText().trim();
        
        // Validaciones básicas
        if (rut.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un RUT", "Error", JOptionPane.ERROR_MESSAGE);
            tf_RutEmpleado.requestFocus();
            return;
        }
        
        if (!bd.verificarRutExiste(rut)) {
            JOptionPane.showMessageDialog(this, "El RUT ingresado no existe en el sistema", "Error", JOptionPane.ERROR_MESSAGE);
            tf_RutEmpleado.requestFocus();
            return;
        }
        
        if (fechaInicio == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de inicio", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (fechaFin == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha de fin", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (fechaInicio.after(fechaFin)) {
            JOptionPane.showMessageDialog(this, "La fecha de inicio debe ser anterior o igual a la fecha de fin", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (motivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un motivo para la ausencia", "Error", JOptionPane.ERROR_MESSAGE);
            ta_Motivo.requestFocus();
            return;
        }
        
        // Registrar la ausencia
        try {
            java.sql.Date sqlFechaInicio = new java.sql.Date(fechaInicio.getTime());
            java.sql.Date sqlFechaFin = new java.sql.Date(fechaFin.getTime());
            
            String motivoCompleto = tipoAusencia + ": " + motivo;
            
            // Intentar registrar en la base de datos
            if (bd.registrarAusenciaLicencia(rut, motivoCompleto, sqlFechaInicio, sqlFechaFin)) {
                String nombreEmpleado = bd.obtenerNombreUsuario(rut);
                
                // Calcular días de ausencia
                long diferenciaTiempo = fechaFin.getTime() - fechaInicio.getTime();
                int diasAusencia = (int) (diferenciaTiempo / (1000 * 60 * 60 * 24)) + 1;
                
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, 
                    "Ausencia registrada exitosamente\\n\\n" +
                    "Empleado: " + nombreEmpleado + "\\n" +
                    "Tipo: " + tipoAusencia + "\\n" +
                    "Días de ausencia: " + diasAusencia + "\\n" +
                    "Período: " + sdf.format(fechaInicio) + " al " + sdf.format(fechaFin),
                    "Registro Exitoso", 
                    JOptionPane.INFORMATION_MESSAGE);
                
                // Limpiar formulario después del registro exitoso
                limpiarFormulario();
                
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Error al registrar la ausencia. Verifique la conexión con la base de datos.", 
                    "Error de Base de Datos", 
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, 
                "Error inesperado: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
   private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {
    this.dispose();
    
    // USAR SesionUsuario
    if (Sesion_Usuario.hayUsuarioLoggeado()) {
        new Interfaz_Asistencia(Sesion_Usuario.getUsuario()).setVisible(true);
    } else {
        Usuario usuarioTemp = new Usuario();
        usuarioTemp.setNombre("Usuario Temp");
        new Interfaz_Asistencia(usuarioTemp).setVisible(true);
    }
}


    
    // ============= MÉTODO AUXILIAR =============
    
    private void limpiarFormulario() {
        tf_RutEmpleado.setText("");
        dc_FechaInicio.setDate(null);
        dc_FechaFin.setDate(null);
        cb_TipoAusencia.setSelectedIndex(0);
        ta_Motivo.setText("");
        lbl_NombreEmpleado.setText("Ingrese un RUT para buscar el empleado");
        lbl_NombreEmpleado.setForeground(new java.awt.Color(76, 175, 80));
        tf_RutEmpleado.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_AusenciaLaboral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfaz_AusenciaLaboral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_BuscarEmpleado;
    private javax.swing.JButton btn_RegistrarAusencia;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JComboBox<String> cb_TipoAusencia;
    private com.toedter.calendar.JDateChooser dc_FechaInicio;
    private com.toedter.calendar.JDateChooser dc_FechaFin;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_NombreEmpleado;
    private javax.swing.JTextArea ta_Motivo;
    private javax.swing.JTextField tf_RutEmpleado;
    // End of variables declaration                   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
