/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_de_asistencia;

import Clases.Usuario;
import Clases_BD.Comm_BD;
import javax.swing.JOptionPane;

/**
 *
 * @author dolan
 */
public class Interfaz_Editar_Usuarios extends javax.swing.JFrame {
    private Usuario U_aEditar;
    Comm_BD Bd;

    /**
     * Creates new form Interfaz_ModificarU
     */
    public Interfaz_Editar_Usuarios(Usuario U) {
        initComponents();
        Bd = new Comm_BD();
        U_aEditar = U;
        U_Modificar.setText(U_aEditar.getRut() );
        
        CambiarDato.setEnabled(false);
        tit_Contra.setVisible(false);
        tf_Contra.setVisible(false);
        
        Titulo_Anterior.setText("Nombre");
        Titulo_Nuevo.setText("Nombre");
        DatoAnterior.setText(U_aEditar.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        U_Modificar = new javax.swing.JLabel();
        CB_Datos = new javax.swing.JComboBox<>();
        DatoNuevo = new javax.swing.JTextField();
        DatoAnterior = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Titulo_Anterior = new javax.swing.JLabel();
        Titulo_Nuevo = new javax.swing.JLabel();
        CambiarDato = new javax.swing.JButton();
        tf_Contra = new javax.swing.JTextField();
        tit_Contra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Que Informacion desea modificar del usuario:");

        U_Modificar.setBackground(new java.awt.Color(255, 255, 255));
        U_Modificar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        U_Modificar.setForeground(new java.awt.Color(255, 255, 255));
        U_Modificar.setText("Usuario a Editar");

        CB_Datos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido", "correo", "contraseña" }));
        CB_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_DatosActionPerformed(evt);
            }
        });

        DatoAnterior.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        DatoAnterior.setForeground(new java.awt.Color(255, 255, 255));
        DatoAnterior.setText("maria.gomez@ejemplo.com");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Datos a Cambiar");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Anterior");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nuevo");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seleccione el");

        Titulo_Anterior.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_Anterior.setText("---");

        Titulo_Nuevo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_Nuevo.setText("---");

        CambiarDato.setText("Cambiar");
        CambiarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarDatoActionPerformed(evt);
            }
        });

        tit_Contra.setForeground(new java.awt.Color(255, 255, 255));
        tit_Contra.setText("Reingrese su Contraseña");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese el");

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(U_Modificar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CB_Datos, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(DatoNuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(DatoAnterior, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Titulo_Anterior, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Titulo_Nuevo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(CambiarDato, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tf_Contra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(tit_Contra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(Cancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(U_Modificar))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(CB_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(Cancelar)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(CambiarDato)
                        .addGap(159, 159, 159))))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DatoAnterior)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(Titulo_Anterior)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(50, 50, 50)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(Titulo_Nuevo)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(DatoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 106, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tit_Contra)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(U_Modificar))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(CB_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addComponent(CambiarDato))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(tit_Contra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tf_Contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(Titulo_Nuevo)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DatoNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Titulo_Anterior)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DatoAnterior))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_DatosActionPerformed
        // TODO add your handling code here:
        String Dato = CB_Datos.getSelectedItem().toString();
        CambiarDato.setEnabled(true);
        
        switch (Dato) {
            case "nombre":
               
                tit_Contra.setVisible(false);
                tf_Contra.setVisible(false);
                
                Titulo_Anterior.setText("Nombre");
                Titulo_Nuevo.setText("Nombre");
                DatoAnterior.setText(U_aEditar.getNombre());
                break;
                
            case "apellido":
                tit_Contra.setVisible(false);
                tf_Contra.setVisible(false);
                Titulo_Anterior.setText("Apellido");
                Titulo_Nuevo.setText("Apellido");
                DatoAnterior.setText(U_aEditar.getApellido());
                break;
            case "correo":
                tit_Contra.setVisible(false);
                tf_Contra.setVisible(false);
                Titulo_Anterior.setText("Correo");
                Titulo_Nuevo.setText("Correo");
                DatoAnterior.setText(U_aEditar.getCorreo());
                break;
            case "contraseña":
                tit_Contra.setVisible(true);
                tf_Contra.setVisible(true);
                Titulo_Anterior.setText("Contraseña");
                Titulo_Nuevo.setText("Contraseña");
                DatoAnterior.setText(" ");
                break;
        }
        
    }//GEN-LAST:event_CB_DatosActionPerformed

    private void CambiarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarDatoActionPerformed
        // TODO add your handling code here:
        String Dato = CB_Datos.getSelectedItem().toString();
        if(!DatoNuevo.getText().isEmpty()){
            int Opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Deseas Cambiar el " + Dato + " a: " + DatoNuevo.getText() + "?",
                    "Confirmar",
                    JOptionPane.YES_NO_OPTION
                );

                if (Opcion == JOptionPane.YES_OPTION) {
                    switch (Dato) {
                        case "nombre":
                            String Nombre = DatoNuevo.getText();
                            Bd.Dao_ModificarUsuario(Dato , Nombre , U_aEditar.getRut());
                            JOptionPane.showMessageDialog(rootPane, "Dato Cambiado con exito", "Exito", HEIGHT);
                            break;
                            
                        case "apellido":
                            String Apellido = DatoNuevo.getText();
                            Bd.Dao_ModificarUsuario(Dato , Apellido , U_aEditar.getRut());
                            JOptionPane.showMessageDialog(rootPane, "Dato Cambiado con exito", "Exito", HEIGHT);
                            break;
                        case "correo":
                            String Correo = DatoNuevo.getText();
                            Bd.Dao_ModificarUsuario(Dato , Correo , U_aEditar.getRut());
                            JOptionPane.showMessageDialog(rootPane, "Dato Cambiado con exito", "Exito", HEIGHT);
                            break;
                        case "contraseña":
                            String Contrasena = DatoNuevo.getText();
                            String Comprobar = tf_Contra.getText();
                            if (Contrasena.equals(Comprobar)){
                                Bd.Dao_ModificarUsuario("contrasena" , Contrasena , U_aEditar.getRut());
                                JOptionPane.showMessageDialog(rootPane, "Dato Cambiado con exito", "Exito", HEIGHT);
                                break;
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Contraseña no coincide", "Contraseña Erronea", HEIGHT);
                                break;
                            }
                        }
                }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Ingrese un Dato para Actualizar", "Cuadro Vacio", HEIGHT);
        }
        

    }//GEN-LAST:event_CambiarDatoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Datos;
    private javax.swing.JButton CambiarDato;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel DatoAnterior;
    private javax.swing.JTextField DatoNuevo;
    private javax.swing.JLabel Titulo_Anterior;
    private javax.swing.JLabel Titulo_Nuevo;
    private javax.swing.JLabel U_Modificar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField tf_Contra;
    private javax.swing.JLabel tit_Contra;
    // End of variables declaration//GEN-END:variables
}
